name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Charm Under Test
        uses: actions/download-artifact@v4
        with:
          name: built-charm
          path: built/
      
      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find built/ -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: lxd
          lxd-channel: 5.20/stable

      - name: Install tox
        run: pip install tox

      - name: Run integration tests
        run: |
          tox -e integration -- \
            --charm_path="${{ steps.charm-path.outputs.charm_path }}" \
